name: Hack Web3Conf Submission
description: Make your submission to Hack Web3Conf
title: "Submission: <team name>"
labels: ["submission"]
body:
  - type: input
    id: team-name
    attributes:
      label: Team Name
    validations:
      required: true
  - type: textarea
    id: team-members
    attributes:
      label: Team members (if changed)
      description: Mention details of all team members in case there is a change
      value: |
        Member #1
        Name:
        Email:
        Twitter handle:
        Discord ID (with #tag);
  - type: input
    id: project-name
    attributes:
      label: Project Name
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: project-track
    attributes:
      label: Project Track
      description: For which track are you submitting your project?
      options:
          - All Things Devs
          - NFT, Art & Gaming
          - Blockchain & Cryptocurrencies
          - DeFi
          - Community
          - Hack for Women
          - Education
    validations:
      required: false
  - type: dropdown
    id: bounty
    attributes:
      label: Sponsor Bounties
      description: Which sponsor bounties are you applying for?
      multiple: true
      options:
        - IPFS Filecoin
        - Alchemy
        - Gitopia
    validations:
      required: false
  - type: input
    id: project-repo
    attributes:
      label: Link to project GitHub public repo
    validations:
      required: true
  - type: input
    id: website-link
    attributes:
      label: Link to project website
    validations:
      required: true
  - type: input
    id: demo-link
    attributes:
      label: Link to demo video
    validations:
      required: true
  - type: textarea
    id: contract-addresses
    attributes:
      label: Contract address
      description: List all the deployed contract addresses
    validations:
      required: false
  - type: textarea
    id: inspiration
    attributes:
      label: Inspiration
      description: What was your inspiration behind making this project?
    validations:
      required: false
  - type: textarea
    id: what-it-does
    attributes:
      label: What it does
      description: Explain in short what your project does
    validations:
      required: false
  - type: textarea
    id: challenges-you-ran-into
    attributes:
      label: Challenges you ran into
      description: What challenges did you face during this hack?
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Anything else you that you want to share with us?
        
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
